### ISSUE TITLE
whatprovides StringIO does not work on Windows

### ISSUE THREAD

**Issue by shmakovpn** [shmakovpn/whatprovides#1]
Error
Traceback (most recent call last):
  File "C:\Users\shmakovpn\AppData\Local\Continuum\anaconda3\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\shmakovpn\AppData\Local\Continuum\anaconda3\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\shmakovpn\projects\whatprovides\whatprovides\tests.py", line 164, in test_string_io
    for result in results:
  File "C:\Users\shmakovpn\projects\whatprovides\whatprovides\whatprovides.py", line 115, in filter_declaration
    for declaration in declarations:
  File "C:\Users\shmakovpn\projects\whatprovides\whatprovides\whatprovides.py", line 184, in get_declarations
    for line in lines:
  File "C:\Users\shmakovpn\projects\whatprovides\whatprovides\whatprovides.py", line 209, in get_file_lines
    for line in file:
  File "C:\Users\shmakovpn\AppData\Local\Continuum\anaconda3\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 884: character maps to <undefined>

**Comment by shmakovpn** [comment]
Solved, tests updated

**Comment by shmakovpn** [comment]
Solved, tests updated
